# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pedabook' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  rn_path = '../node_modules/react-native'
  # Pods for pedabook
  pod 'rn-fetch-blob',
    :path => '../node_modules/rn-fetch-blob'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
